version: "3.0"
services:
  app-sba:
    build:
      context: ./roncoo-education-app-sba
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-app-sba
    container_name: sba
    restart: always
    volumes:
      - /home/roncoo/logs/sba:/root/logs/sba
    networks:
      - education
    ports:
      - "8182:8182"
  app-job:
    build:
      context: ./roncoo-education-app-job
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-app-job
    container_name: job
    restart: always
    volumes:
      - /home/roncoo/logs/job:/root/logs/job
    networks:
      - education
    ports:
      - "8181:8181"
  app-gateway:
    build:
      context: ./roncoo-education-app-gateway
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-app-gateway
    container_name: gateway
    restart: always
    volumes:
      - /home/roncoo/logs/gateway:/root/logs/gateway
    networks:
      - education
    ports:
      - "8180:8180"
  system-service:
    build:
      context: ./roncoo-education-system/roncoo-education-system-service
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-system-service
    container_name: system
    restart: always
    volumes:
      - /home/roncoo/logs/system:/root/logs/system
    networks:
      - education
    ports:
      - "8184:8184"
  user-service:
    build:
      context: ./roncoo-education-user/roncoo-education-user-service
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-user-service
    container_name: user
    restart: always
    volumes:
      - /home/roncoo/logs/user:/root/logs/user
    networks:
      - education
    ports:
      - "8186:8186"
  course-service:
    build:
      context: ./roncoo-education-course/roncoo-education-course-service
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=192.168.100.11:8848'
    image: roncoo-education-course-service
    container_name: course
    restart: always
    volumes:
      - /home/roncoo/logs/course:/root/logs/course
    networks:
      - education
    ports:
      - "8188:8188"
networks:
  education:
    driver: bridge
