version: "3"
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    network_mode: host
  redis:
    image: redis:6
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    command: [ "redis-server","--appendonly", "yes", "--requirepass", "123456" ]
    network_mode: host
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    privileged: true
    restart: always
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    network_mode: host
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=localhost
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=os_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - TOMCAT_ACCESSLOG_ENABLED=false
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    network_mode: host
    depends_on:
      - mysql
  seata:
    image: seataio/seata-server:1.6.1
    container_name: seata
    restart: always
    volumes:
      - ./seata/logs:/root/logs
      - ./seata/conf/application.yml:/seata-server/resources/application.yml
    depends_on:
      - nacos
      - redis
    network_mode: host
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/etc/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    network_mode: host
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ "server", "/data", "--console-address", ":9001" ]
    network_mode: host
  job:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: job
    restart: always
    volumes:
      - ./job/logs:/data/applogs
    environment:
      PARAMS: '--server.port=8080 --server.servlet.context-path=/job 
      --spring.datasource.url=jdbc:mysql://localhost:3306/os_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      --spring.datasource.username=root
      --spring.datasource.password=123456
      --xxl.job.accessToken=education-job'
    network_mode: host
